#!/bin/sh -v

RPI4_DIR=$(pwd)

cd ../../../..
make \
  CROSS_COMPILE64=/opt/toolchain/gcc-arm-10.3-2021.07-x86_64-aarch64-none-linux-gnu/bin/aarch64-none-linux-gnu- \
  PLATFORM=rpi4 \
  CFG_ARM64_core=y \
  CFG_DT=y \
  CFG_TEE_CORE_LOG_LEVEL=4

cd ${RPI4_DIR}
